export const AllItem = [
    {
        id:1,
        img:'product/pr1.avif'
    },
    {
        id:2,
        img:'/product/pr2.avif'
    },
    {
        id:3,
        img:'/product/pr3.avif'
    },
    {
        id:4,
        img:'/product/pr4.avif'
    },
    {
        id:5,
        img:'/product/pr5.avif'
    },
    {
        id:6,
        img:'/product/pr6.avif'
    },
    {
        id:7,
        img:'/product/pr7.avif'
    },
    {
        id:8,
        img:'/product/pr8.avif'
    },
    {
        id:9,
        img:'/product/pr9.avif'
    },
    {
        id:10,
        img:'/product/pr10.avif'
    },
    {
        id:11,
        img:'/product/electronics.avif'
    },
    {
        id:12,
        img:'/product/kitchen.avif'
    },
    {
        id:13,
        img:'/product/skincare1.avif'
    },
    {
        id:14,
        img:'/product/skincare2.avif'
    },
    {
        id:15,
        img:'/product/skincare3.avif'
    },
]