export const HomeProduct = [
  {
    id: 1,
    img: "/product/pr1.avif",
    name: "Ergonomic Pillow",
    type: "Furniture",
    price: "₱ 2990",
  },
  {
    id: 2,
    img: "/product/skincare2.avif",
    name: "Ergonomic Pillow",
    type: "Skincare",
    price: "₱ 2990",
  },
  {
    id: 4,
    img: "/product/kitchen2.avif",
    name: "Ergonomic Pillow",
    type: "Kitchen",
    price: "₱ 2990",
  },
  {
    id: 5,
    img: "/product/electronics.avif",
    name: "Ergonomic Pillow",
    type: "Electronics",
    price: "₱ 2990",
  },
];

export const AllProducts = [
  {
    id: 1,
    img: "/product/pr1.avif",
    category:'Furniture',
    name: "KVARNVEN",
    description: "Ergonomic pillow, side/back sleeper,",
    type: "Furnitures",
    price: "₱ 580",
  },
  {
    id: 2,
    img: "/product/pr2.avif",
    category:'Furniture',
    name: "RÄCKLA",
    description: "Bag, foldable, black,",
    type: "Furnitures",
    price: "₱ 390",
  },
  {
    id: 3,
    img: "/product/pr3.avif",
    category:'Furniture',
    name: "REXBEGONIA",
    description: "Cooling pad",
    type: "Furnitures",
    price: "₱ 490",
  },
  {
    id: 4,
    img: "/product/pr4.avif",
    category:'Furniture',
    name: "RENSARE",
    description: "Waterproof Bag",
    type: "Furnitures",
    price: "₱ 390",
  },
  {
    id: 5,
    img: "/product/pr5.avif",
    category:'Furniture',
    name: "KNALLA",
    description: "Laundry Bag",
    type: "Furnitures",
    price: "₱ 150",
  },
  {
    id: 6,
    img: "/product/pr6.avif",
    category:'Furniture',
    name: "Wooden Cabinet",
    description: "Height 182cm x Width 121cm",
    type: "Furnitures",
    price: "₱ 1870",
  },
  {
    id: 7,
    img: "/product/pr7.avif",
    category:'chairs',
    name: "Wooden Chair",
    description: "Chair",
    type: "Furnitures",
    price: "₱ 750",
  },
  {
    id: 8,
    img: "/product/pr8.avif",
    category:'chairs',
    name: "Curve Chair",
    description: "Chair",
    type: "Furnitures",
    price: "₱ 750",
  },
  {
    id: 9,
    img: "/product/pr9.avif",
    category:'chairs',
    name: "Mini Chair",
    description: "Chair",
    type: "Furnitures",
    price: "₱ 750",
  },
  {
    id: 10,
    img: "/product/pr10.avif",
    category:'Furniture',
    name: "Lampshade",
    description: "Aesthetic Lamp",
    type: "Furnitures",
    price: "₱ 550",
  },
  {
    id: 11,
    img: "/product/electronics.avif",
    category:'electronics',
    name: "BM3 Headset",
    description: "Skyblue colored",
    type: "Electronics",
    price: "₱ 1120",
  },
  {
    id: 12,
    img: "/product/kitchen.avif",
    category:'kitchen',
    name: "Oven Toaster",
    description: "High Quality Oven Toaster",
    type: "Furnitures",
    price: "₱ 3400",
  },
  {
    id: 13,
    img: "/product/kitchen2.avif",
    category:'kitchen',
    name: "Toaster",
    description: "High Quality Toaster",
    type: "Furnitures",
    price: "₱ 1250",
  },
  {
    id: 14,
    img: "/product/skincare1.avif",
    category:'skincare',
    name: "Body Lotion",
    description: "Lotion",
    type: "Furnitures",
    price: "₱ 860",
  },
  {
    id: 15,
    img: "/product/skincare2.avif",
    category:'skincare',
    name: "Vitaskin",
    description: "Lotion",
    type: "Furnitures",
    price: "₱ 1550 Package",
  },
  {
    id: 16,
    img: "/product/skincare3.avif",
    category:'skincare',
    name: "Moisturizer",
    description: "Moisturizer",
    type: "Furnitures",
    price: "₱ 1120",
  },
];

export const FurnitureItems = [
    {
        id: 1,
        img: "/product/pr5.avif",
        name: "KNALLA",
        description: "Laundry Bag",
        type: "Furnitures",
        price: "₱ 150",
      },
      
      {
        id: 2,
        img: "/product/pr3.avif",
        name: "REXBEGONIA",
        description: "Cooling pad",
        type: "Furnitures",
        price: "₱ 490",
      },

      {
        id: 3,
        img: "/product/pr7.avif",
        name: "Wooden Chair",
        description: "Chair",
        type: "Furnitures",
        price: "₱ 750",
      },
      {
        id: 4,
        img: "/product/pr4.avif",
        name: "RENSARE",
        description: "Waterproof Bag",
        type: "Furnitures",
        price: "₱ 390",
      },
     
      {
        id: 5,
        img: "/product/pr1.avif",
        name: "KVARNVEN",
        description: "Ergonomic pillow, side/back sleeper,",
        type: "Furnitures",
        price: "₱ 580",
      },
      {
        id: 6,
        img: "/product/pr6.avif",
        name: "Wooden Cabinet",
        description: "Height 182cm x Width 121cm",
        type: "Furnitures",
        price: "₱ 1870",
      },

      {
        id: 7,
        img: "/product/pr2.avif",
        name: "RÄCKLA",
        description: "Bag, foldable, black,",
        type: "Furnitures",
        price: "₱ 390",
      },
     
      {
        id: 8,
        img: "/product/pr8.avif",
        name: "Curve Chair",
        description: "Chair",
        type: "Furnitures",
        price: "₱ 750",
      },
      {
        id: 9,
        img: "/product/pr9.avif",
        name: "Mini Chair",
        description: "Chair",
        type: "Furnitures",
        price: "₱ 750",
      },
      {
        id: 10,
        img: "/product/pr10.avif",
        name: "Lampshade",
        description: "Aesthetic Lamp",
        type: "Furnitures",
        price: "₱ 550",
      },

]
